namespace TownOfUs.CustomOption {
    public enum SettingsEnum {
        CrewInvestigativeRoles,
        AurialOn,
        DetectiveOn,
        HaunterOn,
        InvestigatorOn,
        LookoutOn,
        MysticOn,
        OracleOn,
        SeerOn,
        SnitchOn,
        SpyOn,
        TrackerOn,
        TrapperOn,

        CrewKillingRoles,
        DeputyOn,
        HunterOn,
        JailorOn,
        SheriffOn,
        VeteranOn,
        VigilanteOn,

        CrewProtectiveRoles,
        AltruistOn,
        MedicOn,
        WardenOn,

        CrewSupportRoles,
        EngineerOn,
        ImitatorOn,
        MediumOn,
        PoliticianOn,
        ProsecutorOn,
        SwapperOn,
        TransporterOn,


        NeutralBenignRoles,
        AmnesiacOn,
        GuardianAngelOn,
        SurvivorOn,

        NeutralEvilRoles,
        DoomsayerOn,
        ExecutionerOn,
        JesterOn,
        PhantomOn,
        SoulCollectorOn,

        NeutralKillingRoles,
        ArsonistOn,
        JuggernautOn,
        PlaguebearerOn,
        GlitchOn,
        JackalOn,
        WerewolfOn,

        ImpostorConcealingRoles,
        EscapistOn,
        GrenadierOn,
        MorphlingOn,
        SwooperOn,
        VenererOn,

        ImpostorKillingRoles,
        BomberOn,
        ScavengerOn,
        TraitorOn,
        WarlockOn,

        ImpostorSupportRoles,
        BlackmailerOn,
        HypnotistOn,
        JanitorOn,
        MinerOn,
        UndertakerOn,

        CrewmateModifiers,
        AftermathOn,
        BaitOn,
        DiseasedOn,
        FrostyOn,
        MultitaskerOn,
        TorchOn,

        GlobalModifiers,
        ButtonBarryOn,
        FlashOn,
        GiantOn,
        LoversOn,
        MiniOn,
        RadarOn,
        ShyOn,
        SixthSenseOn,
        SleuthOn,
        TiebreakerOn,

        ImpostorModifiers,
        DisperserOn,
        DoubleShotOn,
        SaboteurOn,
        UnderdogOn,

        RoleListSettings,
        UniqueRoles,
        Slot1,
        Slot2,
        Slot3,
        Slot4,
        Slot5,
        Slot6,
        Slot7,
        Slot8,
        Slot9,
        Slot10,
        Slot11,
        Slot12,
        Slot13,
        Slot14,
        Slot15,

        MapSettings,
        RandomMapEnabled,
        RandomMapSkeld,
        RandomMapMira,
        RandomMapPolus,
        RandomMapAirship,
        RandomMapFungle,
        RandomMapSubmerged,
        RandomMapLevelImpostor,
        SmallMapHalfVision,
        SmallMapDecreasedCooldown,
        LargeMapIncreasedCooldown,
        SmallMapIncreasedShortTasks,
        SmallMapIncreasedLongTasks,
        LargeMapDecreasedShortTasks,
        LargeMapDecreasedLongTasks,

        BetterPolusSettings,
        VentImprovements,
        VitalsLab,
        ColdTempDeathValley,
        WifiChartCourseSwap,

        CustomGameSettings,
        ColourblindComms,
        CamoCommsKillAnyone,
        ImpostorSeeRoles,
        DeadSeeRoles,
        InitialCooldowns,
        ParallelMedScans,
        SkipButtonDisable,
        FirstDeathShield,
        NeutralEvilWinEndsGame,
        CrewKillersContinue,

        TaskTrackingSettings,
        SeeTasksDuringRound,
        SeeTasksDuringMeeting,
        SeeTasksWhenDead,

        Assassin,
        NumberOfImpostorAssassins,
        NumberOfNeutralAssassins,
        AmneTurnImpAssassin,
        AmneTurnNeutAssassin,
        TraitorCanAssassin,
        AssassinKills,
        AssassinMultiKill,
        AssassinCrewmateGuess,
        AssassinGuessNeutralBenign,
        AssassinGuessNeutralEvil,
        AssassinGuessNeutralKilling,
        AssassinGuessImpostors,
        AssassinGuessModifiers,
        AssassinGuessLovers,

        Aurial,
        AuraInnerRadius,
        AuraOuterRadius,
        SenseDuration,

        Detective,
        ExamineCooldown,
        DetectiveReportOn,
        DetectiveRoleDuration,
        DetectiveFactionDuration,

        Haunter,
        HaunterTasksRemainingClicked,
        HaunterTasksRemainingAlert,
        HaunterRevealsNeutrals,
        HaunterCanBeClickedBy,

        Investigator,
        FootprintSize,
        FootprintInterval,
        FootprintDuration,
        AnonymousFootPrint,
        VentFootprintVisible,

        Lookout,
        WatchCooldown,
        LoResetOnNewRound,
        MaxWatches,

        Mystic,
        MysticArrowDuration,

        Oracle,
        ConfessCooldown,
        RevealAccuracy,
        NeutralBenignShowsEvil,
        NeutralEvilShowsEvil,
        NeutralKillingShowsEvil,

        Seer,
        SeerCooldown,
        CrewKillingRed,
        NeutBenignRed,
        NeutEvilRed,
        NeutKillingRed,
        TraitorColourSwap,

        Snitch,
        SnitchSeesNeutrals,
        SnitchTasksRemaining,
        SnitchSeesImpInMeeting,
        SnitchSeesTraitor,

        Spy,
        WhoSeesDead,

        Tracker,
        UpdateInterval,
        TrackCooldown,
        ResetOnNewRound,
        MaxTracks,

        Trapper,
        MinAmountOfTimeInTrap,
        TrapCooldown,
        TrapsRemoveOnNewRound,
        MaxTraps,
        TrapSize,
        MinAmountOfPlayersInTrap,

        Hunter,
        HunterKillCd,
        HunterStalkCd,
        HunterStalkDuration,
        HunterStalkUses,
        RetributionOnVote,
        HunterBodyReport,

        Jailor,
        JailCooldown,
        MaxExecutes,

        Sheriff,
        SheriffKillOther,
        SheriffKillsNE,
        SheriffKillsNK,
        SheriffKillCd,
        SheriffBodyReport,

        Veteran,
        KilledOnAlert,
        AlertCooldown,
        AlertDuration,
        MaxAlerts,

        Vigilante,
        VigilanteKills,
        VigilanteMultiKill,
        VigilanteGuessNeutralBenign,
        VigilanteGuessNeutralEvil,
        VigilanteGuessNeutralKilling,
        VigilanteGuessModifiers,
        VigilanteGuessLovers,

        Altruist,
        ReviveDuration,
        AltruistTargetBody,

        Medic,
        ShowShielded,
        WhoGetsNotification,
        ShieldBreaks,
        MedicReportSwitch,
        MedicReportNameDuration,
        MedicReportColorDuration,

        Engineer,
        MaxFixes,

        Imitator,
        ImitatorCanBecomePresident,

        Medium,
        MediateCooldown,
        ShowMediatePlayer,
        ShowMediumToDead,
        DeadRevealed,

        Politician,
        CampaignCooldown,

        Prosecutor,
        ProsDiesOnIncorrectPros,

        Swapper,
        SwapperButton,

        Transporter,
        TransportCooldown,
        TransportMaxUses,
        TransporterVitals,

        Amnesiac,
        RememberArrows,
        RememberArrowDelay,

        GuardianAngel,
        ProtectCd,
        ProtectDuration,
        ProtectKCReset,
        MaxProtects,
        ShowProtect,
        GaOnTargetDeath,
        GATargetKnows,
        GAKnowsTargetRole,
        EvilTargetPercent,

        Survivor,
        VestCd,
        VestDuration,
        VestKCReset,
        MaxVests,

        Doomsayer,
        ObserveCooldown,
        DoomsayerGuessNeutralBenign,
        DoomsayerGuessNeutralEvil,
        DoomsayerGuessNeutralKilling,
        DoomsayerGuessImpostors,
        DoomsayerCantObserve,

        Executioner,
        OnTargetDead,
        ExecutionerButton,
        ExecutionerTorment,

        Jester,
        JesterButton,
        JesterVent,
        JesterImpVision,
        JesterHaunt,

        Phantom,
        PhantomTasksRemaining,
        PhantomSpook,

        SoulCollector,
        ReapCooldown,
        PassiveSoulCollection,
        SoulsToWin,

        Arsonist,
        DouseCooldown,
        MaxDoused,
        ArsoImpVision,
        IgniteCdRemoved,

        Juggernaut,
        JuggKillCooldown,
        ReducedKCdPerKill,
        JuggVent,

        Plaguebearer,
        InfectCooldown,
        PestKillCooldown,
        PestVent,

        TheGlitch,
        MimicCooldownOption,
        MimicDurationOption,
        HackCooldownOption,
        HackDurationOption,
        GlitchKillCooldownOption,
        GlitchHackDistanceOption,
        GlitchVent,

        Jackal,
        BiteCooldown,
        VampImpVision,
        VampVent,
        NewVampCanAssassin,
        MaxVampiresPerGame,
        CanBiteNeutralBenign,
        CanBiteNeutralEvil,

        Werewolf,
        RampageCooldown,
        RampageDuration,
        RampageKillCooldown,
        WerewolfVent,

        Escapist,
        EscapeCooldown,
        EscapistVent,

        Grenadier,
        GrenadeCooldown,
        GrenadeDuration,
        FlashRadius,
        GrenadierIndicators,
        GrenadierVent,

        Morphling,
        MorphlingCooldown,
        MorphlingDuration,
        MorphlingVent,

        Swooper,
        SwoopCooldown,
        SwoopDuration,
        SwooperVent,

        Venerer,
        AbilityCooldown,
        AbilityDuration,
        SprintSpeed,
        FreezeSpeed,

        Bomber,
        DetonateDelay,
        MaxKillsInDetonation,
        DetonateRadius,
        BomberVent,
        AllImpsSeeBomb,

        Scavenger,
        ScavengeDuration,
        ScavengeIncreaseDuration,
        ScavengeCorrectKillCooldown,
        ScavengeIncorrectKillCooldown,

        Traitor,
        LatestSpawn,
        NeutralKillingStopsTraitor,

        Warlock,
        ChargeUpDuration,
        ChargeUseDuration,

        Blackmailer,
        BlackmailCooldown,
        BlackmailInvisible,
        LatestNonVote,

        Hypnotist,
        HypnotiseCooldown,

        Miner,
        MineCooldown,

        Undertaker,
        DragCooldown,
        UndertakerDragSpeed,
        UndertakerVent,
        UndertakerVentWithBody,

        Bait,
        BaitMinDelay,
        BaitMaxDelay,

        Diseased,
        DiseasedKillMultiplier,

        Frosty,
        ChillDuration,
        ChillStartSpeed,

        Flash,
        FlashSpeed,

        Giant,
        GiantSlow,

        Lovers,
        BothLoversDie,
        LovingImpPercent,
        NeutralLovers,
        ImpLoverKillTeammate,

        Shy,
        InvisDelay,
        TransformInvisDuration,
        FinalTransparency,

        Saboteur,
        ReducedSaboCooldown,

        Underdog,
        UnderdogKillBonus,
        UnderdogIncreasedKC,


        #region  MOJE RZECZY TERA

        Mayor = 728,
        MayorOn,
        MayorVoteBank,
        MayorAnonymous,
        MayorMaximumBank,

        TimeLord,
        TimeLordOn,
        RewindRevive,
        RewindDuration,
        RewindCooldown,
        RewindMaxUses,
        TimeLordVitals,

        Deputy,

        Warden,

        Shifter,
        ShifterOn,
        ShifterCd,
        WhoShifts,
        ShiftedBecomes,
        ShifterCrewmate,
        ShifterShiftsModifiers,

        Speedrunner,
        SpeedrunnerOn,
        SpeedrunnerTasksRemaining,
        SpeedrunnerCommonTask,
        SpeedrunnerShortTask,
        SpeedrunnerLongTask,

        CanBiteImpostors,

        Foreteller,
        ForetellerOn,
        ForetellerObserveCooldown,
        ForetellerGuessNeutralBenign,
        ForetellerGuessNeutralEvil,
        ForetellerGuessNeutralKilling,
        ForetellerGuessImpostors,
        ForetellerAfterVoting,
        ForetellerGuessesToWin,
        ForetellerCantObserve,
        
        Janitor,

        Camouflager,
        CamouflagerOn,
        CamouflagerCooldown,
        CamouflagerDuration,

        Poisoner,
        PoisonerOn,
        PoisonCooldown,
        PoisonDuration,
        PoisonerVent,
        
        DraftModeHeader,
        DraftEnabled,
        RandomButtonEnabled,
        RandomBasesOffChoices,
        PickTime,
        ButtonAmount,

        SyzyfowyAmong,
        CommsDisableTasks,
        TrackDuration,

        #endregion
    }
}